version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_DEFAULT_USER=testuser
    depends_on:
      - backend
    networks:
      - voice-shopping-network

  backend:
    image: voice-shopping-backend:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
    depends_on:
      - mongo
    networks:
      - voice-shopping-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - voice-shopping-network

volumes:
  mongo_data:

networks:
  voice-shopping-network:
    driver: bridge
